# Generated by Django 5.1.2 on 2024-10-20 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(help_text='Given name of the borrower.', max_length=255)),
                ('surname', models.CharField(help_text='Surname of the borrower.', max_length=255)),
                ('entry_school_year', models.CharField(help_text='The school year the borrower started (e.g., 2024/2025).', max_length=9)),
                ('initial_grade', models.PositiveIntegerField(help_text='Initial grade when the borrower started.')),
                ('borrower_class', models.CharField(help_text='Class of the borrower.', max_length=10)),
                ('inactive', models.BooleanField(default=False, help_text='Set to true if the borrower is inactive.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who added this borrower.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowers_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this borrower.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowers_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, help_text='Optional reference to a Django user.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
