# Generated by Django 5.1.2 on 2024-10-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='entry_school_year',
            field=models.CharField(choices=[('2024/2025', '2024/2025'), ('2023/2024', '2023/2024'), ('2022/2023', '2022/2023'), ('2021/2022', '2021/2022'), ('2020/2021', '2020/2021'), ('2019/2020', '2019/2020')], help_text='The school year the borrower started.', max_length=9),
        ),
    ]
