# Generated by Django 5.1.2 on 2024-10-19 11:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for the category, e.g., LTB.', max_length=3, unique=True)),
                ('name', models.CharField(help_text="Category name, e.g., 'Sachbücher Naturwissenschaften Tiere Pflanzen'.", max_length=255)),
                ('colour', models.CharField(help_text="Colour name for the category, e.g., 'green'.", max_length=50)),
                ('colour_code', models.CharField(help_text="Hex colour code representing the colour, e.g., '#ffffff' for white.", max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex colour code (e.g., #000000 for black).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('description', models.TextField(blank=True, help_text='Optional description of the category.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Category',
                'verbose_name_plural': 'Media Categories',
                'ordering': ['code'],
            },
        ),
    ]
