# Generated by Django 5.1.2 on 2024-10-19 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of the library site.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the library site.', null=True)),
                ('opening_hours', models.TextField(blank=True, help_text='Opening hours for the library site.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set to false if the site is deactivated.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Library Site',
                'verbose_name_plural': 'Library Sites',
                'ordering': ['name'],
            },
        ),
    ]
