# Generated by Django 5.1.2 on 2024-10-19 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_librarysite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the media type, e.g., Book, Game, Music CD.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this media type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_types_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this media type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_types_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Type',
                'verbose_name_plural': 'Media Types',
                'ordering': ['name'],
            },
        ),
    ]
