# Generated by Django 5.1.2 on 2024-10-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='legacy_media_number',
            field=models.CharField(blank=True, help_text='Legacy media number (0001-9999).', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_number',
            field=models.CharField(help_text='Automatically generated media number.', max_length=10, unique=True),
        ),
    ]
